spring.application.name=easymail-sender

# mail settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username={sender}
spring.mail.password={app password}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true